# Generated by Django 3.0.7 on 2020-06-10 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'authority',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=200)),
                ('github_account_name', models.CharField(default='', max_length=50)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Authority')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
